services:
  bot:
    image: ${BOT_IMAGE:-almaty-lis-polling-bot:latest}
    container_name: almaty-lis-polling-bot
    env_file:
      - .env
      - secrets.env
    environment:
      DATABASE__HOST: snakefrogcalendarbot-postgres
    volumes:
      - ./secrets.env:/app/secrets.env:ro
    restart: unless-stopped
    networks:
      - snakefrogcalendarbot

networks:
  snakefrogcalendarbot:
    external: true
    name: snakefrogcalendarbot_default
