// <auto-generated />
using System;
using AlmatyLISPollingBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmatyLISPollingBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.BotSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationTimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly>("DefaultPollStopTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("MainAdminUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("bot_settings", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.ChatAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("chat_administrators", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.CurrencyExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("Nominal")
                        .HasColumnType("integer");

                    b.Property<decimal>("TengePerNominal")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("currency_exchange_rates", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.ExcludedTournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("excluded_tournaments", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.ForcedTournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("forced_tournaments", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.PollCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DifficultyForecast")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAvailableAtFirstSlot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailableAtSecondSlot")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PollSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PollSessionId");

                    b.ToTable("poll_candidates", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.PollSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("DesiredTournamentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int?>("ListMessageId")
                        .HasColumnType("integer");

                    b.Property<int?>("PollMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScheduledStopAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StoppedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("TelegramPollId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("poll_sessions", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.ShadowBannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("shadow_banned_users", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.TournamentHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PlayDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SlotTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tournament_history_entries", (string)null);
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.PollCandidate", b =>
                {
                    b.HasOne("AlmatyLISPollingBot.Domain.Entities.PollSession", null)
                        .WithMany("Candidates")
                        .HasForeignKey("PollSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmatyLISPollingBot.Domain.Entities.PollSession", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
